apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ghost
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: "img"
    component: "ghost"
    tier: "web"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: ghost-svc
          servicePort: 2368