apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghost
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: "img"
    component: "ghost"
    tier: "web"
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/etc/ghost"