apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: "img"
    component: "mysql"
    tier: "db"
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/lib/mysql/"