apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: "img"
    component: "mysql"
    tier: "db"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: "img"
      component: "mysql"
      tier: "db"
  volumeMode: Filesystem
  storageClassName: manual