apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: "img"
    component: "ghost"
    tier: "web"
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: "img"
      component: "ghost"
      tier: "web"
  storageClassName: manual
  volumeMode: Filesystem