apiVersion: v1
kind: Secret
metadata:
  name: mysql-passwords
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: "img"
    component: "mysql"
    tier: "db"
type: Opaque
data:
  password: {{ .Values.mysqlPassword | b64enc | quote }}
  root_password: {{ .Values.mysqlRootPassword | b64enc | quote }}