apiVersion: v1
kind: Service
metadata:
  name: ghost-svc
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: "img"
    component: "ghost"
    tier: "web"
spec:
  selector:
    app: "img"
    component: "ghost"
    tier: "web"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2368
