apiVersion: v1
kind: Service
metadata:
  name: ghost-mysql
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: "img"
    component: "mysql"
    tier: "db"
spec:
  selector:
    app: "img"
    component: "mysql"
    tier: "db"
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
